jdk:
  - oraclejdk8

language: scala

scala:
  - 2.13.0-RC2

install:
  - true

branches:
  only:
    - 2.13.0-RC2
    # - master

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
