jdk:
  - openjdk8

language: scala

scala:
  - 2.13.1

install:
  - true

branches:
  only:
    - CompartmentAPIRefactoring

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt clean coverage "testOnly **.SCROLLTestSuite"

after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
