name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt clean coverage test
      
  coverage:
  
   runs-on: ubuntu-latest

   needs: build

   steps:
   - uses: actions/checkout@v2
   - name: Set up JDK 11
     uses: actions/setup-java@v2
     with:
       java-version: '11'
       distribution: 'adopt'
   - name: Codacy Coverage Reporter
     uses: codacy/codacy-coverage-reporter-action@0.2.0
     with:
       project-token: qmaA44jkdAPti5klDwdc
          
