name: Scala CI

on: [push, pull_request]

jobs:
  test-scroll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: adopt
      - name: Print sbt version
        run: sbt --version
      - name: Compile and run tests
        run: sbt compile test
      - name: Check formatting
        run: sbt scalafmtCheckAll scalafmtSbtCheck
      - run: echo "Previous step failed because code is not formatted. Run 'sbt format'"
        if: ${{ failure() }}    
