name: Scala CI

on: [push, pull_request]

jobs:
  test-scroll:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: apt-get update
        run: sudo apt-get update
      - name: Set up openjdk 1.8
        run: sudo apt-get install openjdk-8-jdk
      - name: Print sbt version
        run: sbt --version
      - name: Compile and run tests
        run: sbt clean compile test
      - name: Check formatting
        run: sbt scalafmtCheckAll scalafmtSbtCheck
      - run: echo "Previous step failed because code is not formatted. Run 'sbt format'"
        if: ${{ failure() }}    
